# Generated by Django 4.0.1 on 2022-02-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='standard_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
